### ISSUE TITLE
Choose frontend framework (Vue.js or React)

### ISSUE THREAD

**Issue by myi100** [3del-Technologies/compass-dashboard#2]
- https://medium.com/@TechMagic/reactjs-vs-angular5-vs-vue-js-what-to-choose-in-2018-b91e028fa91d
- https://vuejs.org/v2/guide/comparison.html
- https://www.valuecoders.com/blog/technology-and-apps/vue-js-comparison-angular-react/

**Comment by mwbelyea** [comment]
@Tommycioc I haven't done much of either, but I would choose Vue JS since that's what Paolo recommended. What do you think?

**Comment by mwbelyea** [comment]
We're going with Vue JS

**Comment by Tommycioc** [comment]
Hey Mike, what was your taught?

**Comment by Tommycioc** [comment]
@myi100 @mwbelyea @YukiseKimi I think we can close this issu as we decide to go for Vue.js

**Comment by myi100** [comment]
Sounds good. Closing now.
