### ISSUE TITLE
Create a template for login and registration forms

### ISSUE THREAD

**Issue by myi100** [3del-Technologies/compass-dashboard#3]
![image](https://user-images.githubusercontent.com/2923059/43679411-a5ad1190-97f2-11e8-8e8a-59f8b1f86335.png)

![image](https://user-images.githubusercontent.com/2923059/43679415-baf4ce26-97f2-11e8-8a19-c9cd75ff16b9.png)

![image](https://user-images.githubusercontent.com/2923059/43679473-b3b96648-97f3-11e8-95e5-c0b0b9d12beb.png)

**Comment by myi100** [comment]
- The multi-step registration process will include (a subset of) information used in this google form: https://goo.gl/forms/5yFluSZC1rktmVN53
- Should include validation for email, phone number, and address (using google maps API)
- Login form should use email and password
- More details to follow...

**Comment by myi100** [comment]
Michael ~ 12 - 15 hours

**Comment by Tommycioc** [comment]
Good

**Comment by Tommycioc** [comment]
So with backend 20-25 h😁

**Comment by myi100** [comment]
Update: Manny and I spoke and decided that to save time we should find a login/registration template for vue.js and use that for now. 

@Tommycioc Can you do some research here and find a template or tutorial online?

**Comment by Tommycioc** [comment]
@myi100 I will definitely check it
