### ISSUE TITLE
Create a template for dashboard (with side bar and main panel)

### ISSUE THREAD

**Issue by myi100** [3del-Technologies/compass-dashboard#5]

**Comment by Tommycioc** [comment]
@myi100 Do you have a list of topic you want to get on the dashboard? I just dont see anything with enough details on it except I did miss it. Thanks in advance.

**Comment by myi100** [comment]
For now, the should include:

- Main page
- Profile page
- Organization directory
- FAQ page
- Guides page

But let's touch base on our call on tomorrow to make sure we are on the same page as to what yu mean by topic.
